from pywhispercpp.model import Model # needed for speech to text
import wave # needed to read and write wav files
from piper import PiperVoice # needed for text to speech
import ollama # needed to run the ollama model for generating responses

import pygame # needed to play the wav files generated by piper
import sys # needed for printing errors to stderr
import time # needed for sleep

import sounddevice as sd # needed to record audio from the microphone
import soundfile as sf # needed to save the recorded audio to a wav file
import queue # needed to create a queue for recording audio from the microphone in real time
import numpy as np # needed to convert the recorded audio to a numpy array

import threading # needed for multithreading

class MagicChest:
    """
    This is a class for combining Speech To Text, Text To Speech, and LLM interactions.  

    It's meant to be used to mimic a magic chest for a friends renfaire project
    """

    def __init__(self):
        """
        Basic init method for loading all models in.  
        """

        self.stt_model = Model("tiny.en") # load the whisper model for speech to text
        self.tts_voice = PiperVoice.load("en_US-amy-medium.onnx") # load the piper voice for text to speech
        self.output_wav_path = "output.wav" # set the path for the output wav file
        self.input_wav_path = "input.wav" # set the path for the input wav file

        self.queue = queue.Queue() # create a queue for recording audio from the microphone in real time
        
        pygame.mixer.init() # initialize the pygame mixer for playing audio

        messages = [
            {
                'role': 'user',
                'content': 'Say that you are ready to go.  ',
            },
            ]
        
        # load the ollama model for generating responses and set it to not timeout
        response = ollama.chat(model="gemma3:1b", messages=messages, keep_alive=-1)
        print(response.message.content)
        #print("Magic Chest initialized and ready to use!")


    def callback(self, indata, frames, time, status):
        """This is called (from a separate thread) for each audio block."""
        if status:
            print(status, file=sys.stderr)
        self.queue.put(indata.copy())

    def keyboard_listener(self):
        """
        This is a message to record from the microphone and stop when the user presses CTRL + C
        """

        print("Recording from the microphone. Press CTRL + C to stop recording.")
        try:
            sample_rate = 16000 # set the sample rate for recording (16kHz is required for the whisper model)
            device = sd.query_devices(kind='input')  # get the default input device
            print(f"Using input device: {device['name']}")
            with sf.SoundFile(self.input_wav_path, mode='w', samplerate=sample_rate, channels=1, subtype='PCM_16') as file:
                with sd.InputStream(samplerate=sample_rate, channels=1, dtype='int16', callback=self.callback):
                    while True:
                        file.write(self.queue.get())
        except KeyboardInterrupt:
            print("Stopped recording from the microphone.")

    def stt(self):
        """
        Transcribes the text from the input wav file into text

        Returns:
            str: The transcribed text from the input wav file
        """

        segments = self.stt_model.transcribe(self.input_wav_path) # transcribe the input wav file using the whisper model
        text = " ".join([segment.text for segment in segments]) # combine the transcribed segments into a single string

        print(f"Transcribed text: {text}") # print the transcribed text

        return text
    
    def tts(self, text):
        """
        Synthesizes the input text into speech and saves it to the output wav file

        Args:
            text (str): The text to be synthesized into speech
        """

        with wave.open(self.output_wav_path, "wb") as wav_file: # open the output wav file for writing
            self.tts_voice.synthesize_wav(text, wav_file) # synthesize the input text into speech and save it to the output wav file

        #print(f"Synthesized text: {text}") # print the synthesized text

    def generate_response(self, text):
        """
        Generates a response to the input text using the ollama model

        Args:
            text (str): The text to generate a response to

        Returns:
            str: The generated response from the ollama model
        """

        # TODO: add system prompts to control the behavior of the ollama model and make it more consistent with the theme of a magic chest

        messages = [
            {
                'role': 'user',
                'content': text,
            },
            ]
        
        # generate a response using the ollama model and set it to not timeout
        response = ollama.chat(model="gemma3:1b", messages=messages, keep_alive=-1)
        print(f"Generated response: {response.message.content}") # print the generated response

        return response.message.content
    
    def play_response(self):
        """
        Plays the synthesized response from the output wav file
        """

        sound_object = pygame.mixer.Sound(self.output_wav_path) # load the output wav file as a sound object
        sound_object.play() # play the sound object
        
        while pygame.mixer.get_busy(): # wait for the sound to finish playing
            time.sleep(0.1)


if __name__ == "__main__":
    chest = MagicChest() # create an instance of the MagicChest class

    while True:
        input("Press Enter to start recording from the microphone...") # wait for the user to press Enter to start recording
        chest.keyboard_listener() # start the keyboard listener to record audio from the microphone
        transcribed_text = chest.stt() # transcribe the recorded audio into text
        response = chest.generate_response(transcribed_text) # generate a response to the transcribed text using the ollama model
        chest.tts(response) # synthesize the generated response into speech and save it to the output wav file
        chest.play_response() # play the synthesized response from the output wav file